name: no_std check
on:
  pull_request: {}
  push:
    branches: main

jobs:
  check-no-std-panic-conflict:
    name: Check no_std panic conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cd tools/no-std-check
          make check-panic-conflict

  # Disabled until sp-io removes this feature which was removed in latest nightlies:
  #   https://github.com/paritytech/substrate/blob/b5846ccc8480806aa6035ae4d2e89d61930f697e/primitives/io/src/lib.rs#L22
  # check-substrate:
  #   name: Check no_std substrate support
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: dtolnay/rust-toolchain@stable
  #     - run: |
  #         cd tools/no-std-check
  #         make check-substrate
